format = """
$username\
$sudo\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$aws\
$kubernetes
$status\
$character"""

palette = 'me'

[palettes.me]
std = '75'       # standard blue
ok = '82'        # A-OK green
warn = '214'     # pay-attention orange
sym = '32'       # slightly darker blue
sym-warn = '202' # slightly darker orange
dir = '32'       # directories
user = '240'     # standard user
root = '214'     # root user

[username]
format = '[$user]($style) '
style_user = 'std'
style_root = 'warn'
show_always = false

[directory]
style = 'dir'
truncation_length = 4
truncation_symbol = '.../'
truncate_to_repo = false

[git_branch]
format = '[\($symbol$branch(:$remote_branch)]($style) '
style = 'std'
symbol = '[](sym)'

[git_status]
format = '([$ahead_behind$stashed$staged$modified$renamed$deleted$untracked$conflicted[\)](std)]($style)) '
# $ahead_behind
up_to_date = '[◉](ok)'
ahead      = '[⇡](warn)'
behind     = '[⇣](warn)'
diverged   = '[∆](warn)'
# other statuses
stashed    = '[$](ok)'
staged     = '[+](std)'
modified   = '[m](warn)'
renamed    = '[r](warn)'
deleted    = '[x](warn)'
untracked  = '[?](warn)'
conflicted = '[=](warn)'

[aws]
format = '[\[$symbol($profile)/($region)($duration)\]]($style) '
style = 'std'
symbol = '[](sym)'
expiration_symbol = '✗'
[aws.profile_aliases]
fusionauth-dev = 'dev'
fusionauth-dev-admin = 'dev-admin'
fusionauth-prod = 'prod'
fusionauth-prod-admin = 'prod-admin'
fusionauth-svc-admin = 'svc-admin'

[kubernetes]
disabled = false
format = '[\[$symbol$context:$namespace\]]($style) '
style = 'std'
symbol = '[](sym)'
# docker-desktop = 'docker'
[[kubernetes.contexts]]
context_pattern = 'docker-desktop'
context_alias = 'local'
[[kubernetes.contexts]]
context_pattern = '.*prod.*'
style = 'warn'
symbol = '[k8s](sym-warn)'

[status]
disabled = false
format = '[$status]($style) '
style = 'warn'

[character]
error_symbol = '[»](warn)'
success_symbol = '[»](std)'
