format = """
[](fg:base-bg)\
$os\
$shell\
$username\
$sudo\
[](bg:dir-bg fg:base-bg)\
$directory\
[](bg:git-bg fg:dir-bg)\
$git_branch\
$git_status\
[](bg:aws-bg fg:git-bg)\
$aws\
[](bg:k8s-bg fg:aws-bg)\
$kubernetes\
$terraform\
$python\
[](fg:k8s-bg)
$status\
$character
"""

palette = 'blues'

[palettes.blues]
warn    = '214'
base-fg = '#e0e1dd'
base-bg = '#2f2f42'
dir-bg  = '#12293f'
git-bg  = '#273654'
aws-bg  = '#33465c'
k8s-bg  = '#4f637d'


### Line 1 configs

[os]
disabled = false
style = 'bg:base-bg fg:base-fg'
[os.symbols]
Macos = ' '

[shell]
disabled = false
format = '[$indicator]($style)'
style = 'bg:base-bg fg:warn'
zsh_indicator = ''
bash_indicator = 'bash '
fish_indicator = 'fish '

[username]
format = '[$user ]($style)'
style_user = 'bg:base-bg fg:base-fg'
style_root = 'bg:base-bg fg:warn'
show_always = true

[sudo]
disabled = false
format = '[$symbol]($style)'
style = 'bg:base-bg fg:warn'
symbol = '! '

[directory]
format = "[   $path ]($style)"
style = 'bg:dir-bg fg:base-fg'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
format = '[ $symbol $branch ]($style)'
style = 'bg:git-bg fg:base-fg'
symbol = '[](bg:git-bg fg:base-fg)'

[git_status]
format = '[$ahead_behind $stashed$staged$modified$renamed$deleted$untracked$conflicted]($style)'
style ='bg:git-bg fg:base-fg'
# $ahead_behind status
up_to_date = '[•](bg:git-bg fg:base-fg)'
ahead      = '[󰶼](bg:git-bg fg:warn)'
behind     = '[󰶹](bg:git-bg fg:warn)'
diverged   = '[✘](bg:git-bg fg:warn)'
# other status
stashed    = '[*$count ](bg:git-bg base-fg)'
staged     = '[s$count ](bg:git-bg base-fg)'
modified   = '[m$count ](bg:git-bg warn)'
renamed    = '[r$count ](bg:git-bg warn)'
deleted    = '[d$count ](bg:git-bg warn)'
untracked  = '[u$count ](bg:git-bg warn)'
conflicted = '[=$count ](bg:git-bg warn)'

[aws]
format = '[$symbol($profile)/($region) ]($style)'
style = 'bg:aws-bg fg:base-fg'
symbol = '[   ](bg:aws-bg fg:base-fg)'
[aws.profile_aliases]
fusionauth-dev = 'dev'
fusionauth-dev-admin = 'dev-admin'
fusionauth-prod = 'prod'
fusionauth-prod-admin = 'prod-admin'
fusionauth-svc-admin = 'svc-admin'

[kubernetes]
disabled = false
format = '[$symbol$context:$namespace ]($style)'
style = 'bg:k8s-bg fg:base-fg'
symbol = '[ ⎈ ](bg:k8s-bg fg:base-fg)'
# docker-desktop = 'docker'
[[kubernetes.contexts]]
context_pattern = 'docker-desktop'
context_alias = 'local'
[[kubernetes.contexts]]
context_pattern = '.*prod.*'
style = 'bg:k8s-bg fg:warn'
symbol = '[ ⎈ ](bg:k8s-bg fg:warn)'

[terraform]
format = '[$symbol$workspace ]($style)'
style = 'bg:k8s-bg fg:base-fg'
symbol = ' 󱁢 '

[python]
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = 'bg:k8s-bg fg:base-fg'
symbol = ' '

### Line 2 configs

[status]
disabled = false
format = '[$status]($style) '
style = 'warn'

[character]
error_symbol = '[»](warn)'
success_symbol = '[»](base-fg)'
