format = """
[](fg:user-bg)\
$os\
$username\
[](bg:dir-bg fg:user-bg)\
$directory\
[](bg:git-bg fg:dir-bg)\
$git_branch\
$git_status\
[](bg:aws-bg fg:git-bg)\
$aws\
[](bg:k8s-bg fg:aws-bg)\
$kubernetes\
[](fg:k8s-bg)
$status\
$character
"""

palette = 'me'

[palettes.me]
std = '75'       # standard blue
ok = '82'        # A-OK green
warn = '214'     # pay-attention orange
user-bg = '#2f2f42'
user-fg = '#e0e1dd'
dir-bg = '#12293f'
dir-fg = '#e0e1dd'
git-bg = '#273654'
git-fg = '#e0e1dd'
aws-bg = '#33465c'
aws-fg = '#e0e1dd'
k8s-bg = '#4f637d'
k8s-fg = '#e0e1dd'

[os]
disabled = false
style = 'bg:user-bg fg:user-fg'
[os.symbols]
Macos = ' '

[username]
format = '[$user ]($style)'
style_user = 'bg:user-bg fg:user-fg'
style_root = 'bg:user-bg fg:warn'
show_always = true

[directory]
format = "[   $path ]($style)"
style = 'bg:dir-bg fg:dir-fg'
truncation_length = 4
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
format = '[ $symbol $branch ]($style)'
style = 'bg:git-bg fg:git-fg'
symbol = '[](bg:git-bg fg:git-fg)'

[git_status]
format = '[$ahead_behind $stashed$staged$modified$renamed$deleted$untracked$conflicted]($style)'
# format = '[$all_status$ahead_behind ]($style)'
style ='bg:git-bg fg:git-fg'
# $ahead_behind
up_to_date = '[•](bg:git-bg fg:git-fg)'
ahead      = '[󰶼](bg:git-bg fg:warn)'
behind     = '[󰶹](bg:git-bg fg:warn)'
diverged   = '[✘](bg:git-bg fg:warn)'
# other statuses
stashed    = '[$$count ](bg:git-bg git-fg)'
staged     = '[s$count ](bg:git-bg git-fg)'
modified   = '[m$count ](bg:git-bg warn)'
renamed    = '[r$count ](bg:git-bg warn)'
deleted    = '[d$count ](bg:git-bg warn)'
untracked  = '[u$count ](bg:git-bg warn)'
# conflicted = '[=](warn)'

[aws]
format = '[$symbol($profile)/($region) ]($style)'
style = 'bg:aws-bg fg:aws-fg'
symbol = '[   ](bg:aws-bg fg:aws-fg)'
[aws.profile_aliases]
fusionauth-dev = 'dev'
fusionauth-dev-admin = 'dev-admin'
fusionauth-prod = 'prod'
fusionauth-prod-admin = 'prod-admin'
fusionauth-svc-admin = 'svc-admin'

[kubernetes]
disabled = false
format = '[$symbol$context:$namespace ]($style)'
style = 'bg:k8s-bg fg:k8s-fg'
symbol = '[ ⎈ ](bg:k8s-bg fg:k8s-fg)'
# docker-desktop = 'docker'
[[kubernetes.contexts]]
context_pattern = 'docker-desktop'
context_alias = 'local'
[[kubernetes.contexts]]
context_pattern = '.*prod.*'
style = 'bg:k8s-bg fg:warn'
symbol = '[ ⎈ ](bg:k8s-bg fg:warn)'

[status]
disabled = false
format = '[$status]($style) '
style = 'warn'

[character]
error_symbol = '[»](warn)'
success_symbol = '[»](k8s-bg)'
